global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway-api'
    static_configs:
      - targets: ['gateway-api:8000']
  - job_name: 'risk-manager'
    static_configs:
      - targets: ['risk-manager:8070']
  - job_name: 'execution'
    static_configs:
      - targets: ['execution-ib:8071', 'execution-crypto:8072']
  - job_name: 'feature-pipeline'
    static_configs:
      - targets: ['feature-pipeline:8085']
