name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.7.1
      - name: Configure Poetry
        run: |
          ~/.local/bin/poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          ~/.local/bin/poetry install --without dev
          ~/.local/bin/poetry install --with dev
      - name: Lint
        run: ~/.local/bin/poetry run ruff check .
      - name: Type check
        run: ~/.local/bin/poetry run mypy autollm_trader apps
      - name: Tests
        run: ~/.local/bin/poetry run pytest --cov=autollm_trader --cov=apps --cov-report=xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          exit-code: '0'
